# This playbook install the collectd (http://collectd.org/) server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the collectd and related packages
  yum: pkg={{ item }}
       state=present
  with_items:
    - collectd
    - collectd-rrdtool
    - collectd-sensors
    - collectd-snmp

- name: put configuration for server in place
  template: src=files/collectd-server.j2
            dest=/etc/collectd.conf
            owner=root
            group=root
            mode=0644

- name: create the log file
  command: /usr/bin/touch /var/log/collectd.log

- name: enable collectd on boot and start it
  service: name=collectd
           state=started
           enabled=yes

- name: configure firewall, allow traffic to port 25826
  firewalld: port=25826/udp
             permanent=true
             state=enabled

- name: checkout the source
  command: /usr/bin/git clone git://github.com/pommi/CGP.git /var/www/lighttpd/cgp

- name: set selinux context
  command: /usr/bin/chcon -h unconfined_u:object_r:httpd_log_t:s0 /var/lib/collectd/rrd/

- name: set selinux context
  command: /usr/bin/chcon -R unconfined_u:object_r:httpd_sys_content_t:s0 /var/lib/collectd/rrd
