# This files contains service handlers for Fedora.
#
# Copyright (c) 2013-2015 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage:
#  handlers:
#    - include: handlers/services.yml
#
---
# Control handlers for sshd
- name: start sshd
  service: name=sshd state=started

- name: stop sshd
  service: name=sshd state=stopped

- name: restart sshd
  service: name=sshd state=restarted

# Control handlers for lighttpd
- name: start lighttpd
  service: name=lighttpd state=started

- name: stop lighttpd
  service: name=lighttpd state=stopped

- name: restart lighttpd
  service: name=lighttpd state=restarted

# Control handlers for mysql
- name: start mysql
  service: name=mysqld state=started

- name: stop mysql
  service: name=mysqld state=stopped

- name: restart mysql
  service: name=mysqld state=restarted

# Control handlers for mosquitto
- name: start mosquitto
  service: name=mosquitto state=started

- name: stop mosquitto
  service: name=mosquitto state=stopped

- name: restart mosquitto
  service: name=mosquitto state=restarted
