# This playbook updates the openssl package.
#
# Copyright (c) 2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: fedora
  user: root

  tasks:
  - name: update openssl and related packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - openssl
      - openssl-libs
   notify: 
     - restart lighttpd

  handlers:
   - include: handlers/services.yml
