# This playbook creates a PXE server entry for local startup.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: put a configuration fragement for 'local' in place
  template: src=files/pxe/001-local.j2
            dest=/var/lib/tftpboot/pxelinux.cfg/tmp/001-local
            mode=0644
