# This playbook creates a PXE server entry for CentOS Linux installations.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the a directory for sl
  file: path=/var/lib/tftpboot/sl
        mode=0755
        state=directory

- name: download vmlinuz
  get_url: url=ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/centos/7.0.1406/os/x86_64/isolinux/vmlinuz
           dest=/var/lib/tftpboot/co/vmlinuz
           mode=0644

- name: download initrd
  get_url: url=ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/centos/7.0.1406/os/x86_64/isolinux/initrd.img
           dest=/var/lib/tftpboot/co/initrd.img
           mode=0644

- name: put a configuration fragement for 'centos linux' in place
  template: src=files/pxe/031-co.j2
            dest=/var/lib/tftpboot/pxelinux.cfg/tmp/031-co
            mode=0644
