# This playbook creates a PXE server entry for xPUD (http://www.xpud.org/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the a directory for xpud
  file: path=/var/lib/tftpboot/xpud
        mode=0755
        state=directory

- name: download vmlinuz
  get_url: url=http://mesrss.free.fr/xpud/xpud-{{ xpud_current }}-image
           dest=/var/lib/tftpboot/xpud/xpud-{{ xpud_current }}-image
           mode=0644

- name: put a configuration fragement for 'xpud' in place
  template: src=files/pxe/050-xpud.j2
            dest=/var/lib/tftpboot/pxelinux.cfg/tmp/050-xpud
            mode=0644
