# This playbook creates a PXE server entry for 'menu end'.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: put a configuration fragement for 'menu end' in place
  template: src=files/pxe/0x9-submenu-end.j2
            dest=/var/lib/tftpboot/pxelinux.cfg/tmp/069-submenu-end
            mode=0644
