# This playbook creates a PXE server entry for HDT (http://hdt-project.org).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the a directory for hdt
  file: path=/var/lib/tftpboot/hdt
        mode=0755
        state=directory

- name: download hdt image
  get_url: url=http://hdt-project.org/raw-attachment/wiki/hdt-0.5.0/hdt-0.5.2.img
           dest=/var/lib/tftpboot/hdt/hdt-0.5.2.img
           mode=0755

- name: put a configuration fragement for 'hdt' in place
  template: src=files/pxe/073-hdt.j2
            dest=/var/lib/tftpboot/pxelinux.cfg/tmp/073-hdt
            mode=0644
