# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
# Fedora - http://fedoraporject.org
fedora_previous: 18
fedora_current: 19
fedora_next: 20

# linfo - http://linfo.sourceforge.net/
linfo_version: 1.8.1

# piwik - http://piwik.org/
piwik_version: 1.11.1

# phpsysinfo - http://rk4an.github.com/phpsysinfo/
phpsysinfo_version: 3.1.2

# phpshell - http://phpshell.sourceforge.net/
phpshell_version: 2.4

# phpMyAdmin- http://www.phpmyadmin.net/
phpmyadmin_version: 4.0.5

# DokuWiki - # ani-shell - http://sourceforge.net/projects/ani-shell/
dokuwiki_version: 2013-03-06
