# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
# Fedora - http://fedoraproject.org
fedora_previous: 19
fedora_current: 20
fedora_next: 21

# linfo - http://linfo.sourceforge.net/
linfo_version: 1.9

# piwik - http://piwik.org/
piwik_version: 1.12

# phpsysinfo - http://rk4an.github.com/phpsysinfo/
phpsysinfo_version: 3.1.11

# phpshell - http://phpshell.sourceforge.net/
phpshell_version: 2.4

# phpMyAdmin- http://www.phpmyadmin.net/
phpmyadmin_version: 4.1.14

# DokuWiki - https://www.dokuwiki.org/dokuwiki
dokuwiki_version: 2013-03-06

# Bootstrap - http://getbootstrap.com/
bootstrap_version: 3.1.1
